In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
tickers = ["MSFT", "TSLA", "GOOG", "META"]
start = "2022-08-19"
end   = "2025-12-19"

df = yf.download(tickers, start=start, end=end, interval="1d", auto_adjust=False, group_by="ticker")

[*********************100%***********************]  4 of 4 completed

In [3]:
df

Ticker            MSFT                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2022-08-19  288.899994  289.250000  285.559998  286.149994  278.682800
2022-08-22  282.079987  282.459991  277.220001  277.750000  270.502045
2022-08-23  276.440002  278.859985  275.399994  276.440002  269.226196
2022-08-24  275.410004  277.230011  275.109985  275.790009  268.593201
2022-08-25  277.329987  279.019989  274.519989  278.850006  271.573334
...                ...         ...         ...         ...         ...
2025-12-12  479.820007  482.450012  476.339996  478.529999  478.529999
2025-12-15  480.100006  480.720001  472.519989  474.820007  474.820007
2025-12-16  471.910004  477.890015  470.880005  476.390015  476.390015
2025-12-17  476.910004  480.000000  475.000000  476.119995  476.119995
2025-12-18  478.190002  489.600006  477.890015  483.980011  483.980011

Ticker                      META                                      ...  \
Price         Volume        Open        High         Low       Close  ...
Date                                                                  ...
2022-08-19  20570000  170.199997  172.320007  167.050003  167.960007  ...
2022-08-22  25061100  165.490005  165.490005  162.259995  163.050003  ...
2022-08-23  17527400  162.479996  165.050003  160.699997  161.110001  ...
2022-08-24  18137000  160.600006  165.460007  159.770004  163.259995  ...
2022-08-25  16583400  165.179993  168.880005  164.020004  168.779999  ...
...              ...         ...         ...         ...         ...  ...
2025-12-12  21248100  649.799988  711.000000  638.609985  644.229980  ...
2025-12-15  23727700  645.700012  653.000000  638.700012  647.510010  ...
2025-12-16  20705600  643.500000  662.539978  643.200012  657.150024  ...
2025-12-17  24527200  655.609985  661.229980  649.200012  649.500000  ...
2025-12-18  28518200  657.030029  670.559998  656.460022  664.450012  ...

Ticker            GOOG                                          TSLA  \
Price              Low       Close   Adj Close    Volume        Open
Date
2022-08-19  117.669998  118.120003  117.240669  20187000  299.000000
2022-08-22  114.669998  115.070000  114.213387  19316000  291.913330
2022-08-23  114.300003  114.769997  113.915619  14390700  291.453339
2022-08-24  113.779999  114.699997  113.846130  16051200  297.563324
2022-08-25  115.050003  117.699997  116.823792  14874700  302.359985
...                ...         ...         ...       ...         ...
2025-12-12  306.959991  310.519989  310.519989  21264800  448.089996
2025-12-15  305.739990  309.320007  309.320007  22028900  469.440002
2025-12-16  303.829987  307.730011  307.730011  21285200  472.209991
2025-12-17  297.450012  298.059998  298.059998  29120400  488.220001
2025-12-18  300.630005  303.750000  303.750000  20563800  478.160004

Ticker
Price             High         Low       Close   Adj Close     Volume
Date
2022-08-19  300.359985  292.500000  296.666656  296.666656   61395300
2022-08-22  292.399994  286.296661  289.913330  289.913330   55843200
2022-08-23  298.826660  287.923340  296.453339  296.453339   63984900
2022-08-24  303.646667  296.500000  297.096680  297.096680   57259800
2022-08-25  302.959991  291.600006  296.070007  296.070007   53230000
...                ...         ...         ...         ...        ...
2025-12-12  463.010010  441.670013  458.959991  458.959991   95656700
2025-12-15  481.769989  467.660004  475.309998  475.309998  114542200
2025-12-16  491.500000  465.829987  489.880005  489.880005  107608100
2025-12-17  495.279999  466.200012  467.260010  467.260010  106490400
2025-12-18  490.859985  473.119995  483.369995  483.369995   94870000

[837 rows x 24 columns]

In [4]:
df.columns

MultiIndex([('MSFT',      'Open'),
            ('MSFT',      'High'),
            ('MSFT',       'Low'),
            ('MSFT',     'Close'),
            ('MSFT', 'Adj Close'),
            ('MSFT',    'Volume'),
            ('META',      'Open'),
            ('META',      'High'),
            ('META',       'Low'),
            ('META',     'Close'),
            ('META', 'Adj Close'),
            ('META',    'Volume'),
            ('GOOG',      'Open'),
            ('GOOG',      'High'),
            ('GOOG',       'Low'),
            ('GOOG',     'Close'),
            ('GOOG', 'Adj Close'),
            ('GOOG',    'Volume'),
            ('TSLA',      'Open'),
            ('TSLA',      'High'),
            ('TSLA',       'Low'),
            ('TSLA',     'Close'),
            ('TSLA', 'Adj Close'),
            ('TSLA',    'Volume')],
           names=['Ticker', 'Price'])

In [5]:
tesla = df[('TSLA', 'Close')].values
msft = df[('MSFT',     'Close')].values
google = df[('GOOG',     'Close')].values
meta = df[('META',     'Close')].values
tesla

array([296.66665649, 289.91333008, 296.45333862, 297.09667969,
       296.07000732, 288.08999634, 284.82000732, 277.70001221,
       275.60998535, 277.16000366, 270.20999146, 274.42001343,
       283.70001221, 289.26000977, 299.67999268, 304.42001343,
       292.13000488, 302.60998535, 303.75      , 303.3500061 ,
       309.07000732, 308.73001099, 300.79998779, 288.58999634,
       275.32998657, 276.01000977, 282.94000244, 287.80999756,
       268.20999146, 265.25      , 242.3999939 , 249.44000244,
       240.80999756, 238.13000488, 223.07000732, 222.96000671,
       216.5       , 217.24000549, 221.72000122, 204.99000549,
       219.3500061 , 220.19000244, 222.03999329, 207.27999878,
       214.44000244, 211.25      , 222.41999817, 224.63999939,
       225.08999634, 228.52000427, 227.53999329, 227.82000732,
       214.97999573, 215.30999756, 207.47000122, 197.08000183,
       191.30000305, 177.58999634, 190.72000122, 195.97000122,
       190.94999695, 194.41999817, 186.91999817, 183.16999817,
       180.19000244, 167.86999512, 169.91000366, 183.19999695,
       182.86000061, 182.91999817, 180.83000183, 194.69999695,
       194.69999695, 194.86000061, 182.44999695, 179.82000732,
       174.03999329, 173.44000244, 179.05000305, 167.82000732,
       160.94999695, 156.80000305, 157.66999817, 150.22999573,
       149.86999512, 137.80000305, 137.57000732, 125.34999847,
       123.15000153, 109.09999847, 112.70999908, 121.81999969,
       123.18000031, 108.09999847, 113.63999939, 110.33999634,
       113.05999756, 119.76999664, 118.84999847, 123.22000122,
       123.55999756, 122.40000153, 131.49000549, 128.77999878,
       127.16999817, 133.41999817, 143.75      , 143.88999939,
       144.42999268, 160.27000427, 177.8999939 , 166.66000366,
       173.22000122, 181.41000366, 188.27000427, 189.97999573,
       194.75999451, 196.80999756, 201.28999329, 207.32000732,
       196.88999939, 194.63999939, 209.25      , 214.24000549,
       202.03999329, 208.30999756, 197.36999512, 200.86000061,
       202.07000732, 196.88000488, 207.63000488, 205.71000671,
       202.77000427, 190.8999939 , 197.78999329, 193.80999756,
       187.71000671, 182.        , 172.91999817, 173.44000244,
       174.47999573, 183.25999451, 180.44999695, 184.13000488,
       180.13000488, 183.25      , 197.58000183, 191.1499939 ,
       192.22000122, 190.41000366, 191.80999756, 189.19000244,
       193.88000488, 195.27999878, 207.46000671, 194.77000427,
       192.58000183, 185.52000427, 185.05999756, 184.50999451,
       186.78999329, 180.53999329, 185.8999939 , 185.        ,
       187.03999329, 184.30999756, 180.58999634, 162.99000549,
       165.08000183, 162.55000305, 160.66999817, 153.75      ,
       160.19000244, 164.30999756, 161.83000183, 160.30999756,
       160.61000061, 161.19999695, 170.05999756, 171.78999329,
       169.1499939 , 168.53999329, 172.08000183, 167.97999573,
       166.3500061 , 166.52000427, 173.86000061, 176.88999939,
       180.13999939, 188.86999512, 185.77000427, 182.8999939 ,
       184.47000122, 193.16999817, 201.16000366, 203.92999268,
       207.52000427, 213.97000122, 217.61000061, 221.30999756,
       224.57000732, 234.86000061, 244.3999939 , 249.83000183,
       258.70999146, 256.79000854, 255.8999939 , 260.54000854,
       274.45001221, 259.45999146, 264.60998535, 256.6000061 ,
       241.05000305, 250.21000671, 256.23999023, 257.5       ,
       261.76998901, 279.82000732, 282.48001099, 276.54000854,
       274.42999268, 269.60998535, 269.79000854, 271.98999023,
       277.8999939 , 281.38000488, 290.38000488, 293.33999634,
       291.26000977, 262.8999939 , 260.01998901, 269.05999756,
       265.27999878, 264.3500061 , 255.71000671, 266.44000244,
       267.42999268, 261.07000732, 254.11000061, 259.32000732,
       253.86000061, 251.44999695, 249.69999695, 242.19000244,
       245.33999634, 242.6499939 , 239.75999451, 232.96000671,
       225.6000061 , 219.22000122, 215.49000549, 231.27999878,
       233.19000244, 236.86000061, 230.03999329, 238.58999634,
       238.82000732, 257.17999268, 256.8999939 , 258.07998657,
       245.00999451, 256.48999023, 251.91999817, 251.49000549,
       248.5       , 273.57998657, 267.48001099, 271.29998779,
       276.04000854, 274.39001465, 265.27999878, 266.5       ,
       262.58999634, 255.69999695, 244.88000488, 246.99000549,
       244.11999512, 240.5       , 246.38000488, 250.22000122,
       251.6000061 , 246.52999878, 261.16000366, 260.04998779,
       260.52999878, 259.67001343, 263.61999512, 262.98999023,
       258.86999512, 251.11999512, 253.91999817, 254.8500061 ,
       242.67999268, 220.11000061, 211.99000549, 212.08000183,
       216.52000427, 212.41999817, 205.75999451, 207.30000305,
       197.36000061, 200.83999634, 205.66000366, 218.50999451,
       219.96000671, 219.27000427, 222.17999268, 222.11000061,
       209.97999573, 214.6499939 , 223.71000671, 237.41000366,
       242.83999634, 233.58999634, 234.30000305, 235.6000061 ,
       241.19999695, 234.21000671, 235.44999695, 236.08000183,
       246.72000122, 244.13999939, 240.08000183, 238.83000183,
       235.58000183, 238.72000122, 239.36999512, 242.63999939,
       243.83999634, 239.74000549, 237.00999451, 239.28999329,
       251.05000305, 253.5       , 252.08000183, 257.22000122,
       247.13999939, 254.5       , 252.53999329, 256.60998535,
       261.44000244, 253.17999268, 248.47999573, 248.41999817,
       238.44999695, 237.92999268, 237.49000549, 240.44999695,
       234.96000671, 233.94000244, 227.22000122, 218.88999939,
       219.91000366, 215.55000305, 211.88000488, 212.19000244,
       208.80000305, 209.13999939, 207.83000183, 182.63000488,
       183.25      , 190.92999268, 191.58999634, 187.28999329,
       188.86000061, 187.91000366, 181.05999756, 185.1000061 ,
       187.58000183, 189.55999756, 193.57000732, 188.13000488,
       184.02000427, 188.71000671, 200.44999695, 199.94999695,
       193.75999451, 194.77000427, 197.41000366, 191.97000122,
       199.3999939 , 199.72999573, 202.03999329, 201.88000488,
       202.63999939, 188.13999939, 180.74000549, 176.53999329,
       178.6499939 , 175.33999634, 177.77000427, 177.53999329,
       169.47999573, 162.5       , 163.57000732, 173.80000305,
       171.32000732, 175.66000366, 172.82000732, 170.83000183,
       172.63000488, 177.66999817, 179.83000183, 175.78999329,
       175.22000122, 166.63000488, 168.38000488, 171.11000061,
       164.8999939 , 172.97999573, 176.88000488, 171.75999451,
       174.6000061 , 171.05000305, 161.47999573, 157.11000061,
       155.44999695, 149.92999268, 147.05000305, 142.05000305,
       144.67999268, 162.13000488, 170.17999268, 168.28999329,
       194.05000305, 183.27999878, 179.99000549, 180.00999451,
       181.19000244, 184.75999451, 177.80999756, 174.72000122,
       171.97000122, 168.47000122, 171.88999939, 177.55000305,
       173.99000549, 174.83999634, 177.46000671, 174.94999695,
       186.6000061 , 180.11000061, 173.74000549, 179.24000549,
       176.75      , 176.19000244, 178.78999329, 178.08000183,
       176.28999329, 174.77000427, 175.        , 177.94000244,
       177.47999573, 173.78999329, 170.66000366, 177.28999329,
       182.47000122, 178.00999451, 187.44000244, 184.86000061,
       181.57000732, 183.00999451, 182.58000183, 187.3500061 ,
       196.36999512, 197.41999817, 197.88000488, 209.86000061,
       231.25999451, 246.38999939, 251.52000427, 252.94000244,
       262.32998657, 263.26000977, 241.02999878, 248.22999573,
       252.63999939, 256.55999756, 248.5       , 249.22999573,
       239.19999695, 251.50999451, 246.38000488, 215.99000549,
       220.25      , 219.80000305, 232.1000061 , 222.61999512,
       232.07000732, 216.86000061, 207.66999817, 198.88000488,
       200.63999939, 191.75999451, 198.83999634, 200.        ,
       197.49000549, 207.83000183, 201.38000488, 214.13999939,
       216.11999512, 222.72000122, 221.1000061 , 223.27000427,
       210.66000366, 220.32000732, 213.21000671, 209.21000671,
       205.75      , 206.27999878, 214.11000061, 210.6000061 ,
       219.41000366, 230.16999817, 210.72999573, 216.27000427,
       226.16999817, 228.13000488, 229.80999756, 230.28999329,
       226.77999878, 227.86999512, 227.19999695, 243.91999817,
       238.25      , 250.        , 254.27000427, 257.01998901,
       254.22000122, 260.45999146, 261.63000488, 258.01998901,
       249.02000427, 240.66000366, 250.08000183, 240.83000183,
       244.5       , 241.05000305, 238.77000427, 217.80000305,
       219.16000366, 219.57000732, 221.33000183, 220.88999939,
       220.69999695, 218.8500061 , 217.97000122, 213.6499939 ,
       260.48001099, 269.19000244, 262.51000977, 259.51998901,
       257.54998779, 249.8500061 , 248.97999573, 242.83999634,
       251.44000244, 288.52999878, 296.91000366, 321.22000122,
       350.        , 328.48999023, 330.23999023, 311.17999268,
       320.72000122, 338.73999023, 346.        , 342.02999878,
       339.64001465, 352.55999756, 338.58999634, 338.23001099,
       332.89001465, 345.16000366, 357.08999634, 351.42001343,
       357.92999268, 369.48999023, 389.22000122, 389.79000854,
       400.98999023, 424.76998901, 418.1000061 , 436.23001099,
       463.01998901, 479.85998535, 440.13000488, 436.17001343,
       421.05999756, 430.6000061 , 462.27999878, 454.13000488,
       431.66000366, 417.41000366, 403.83999634, 379.27999878,
       410.44000244, 411.04998779, 394.35998535, 394.94000244,
       394.73999023, 403.30999756, 396.35998535, 428.22000122,
       413.82000732, 426.5       , 424.07000732, 415.10998535,
       412.38000488, 406.57998657, 397.1499939 , 398.08999634,
       389.1000061 , 400.27999878, 404.6000061 , 383.67999268,
       392.20999146, 378.17001343, 374.32000732, 361.61999512,
       350.73001099, 328.5       , 336.51000977, 355.94000244,
       355.83999634, 354.10998535, 360.55999756, 354.3999939 ,
       337.79998779, 330.52999878, 302.79998779, 290.79998779,
       281.95001221, 292.98001099, 284.6499939 , 272.04000854,
       279.1000061 , 263.45001221, 262.67001343, 222.1499939 ,
       230.58000183, 248.08999634, 240.67999268, 249.97999573,
       238.00999451, 225.30999756, 235.86000061, 236.25999451,
       248.71000671, 278.39001465, 288.14001465, 272.05999756,
       273.13000488, 263.54998779, 259.16000366, 268.45999146,
       282.76000977, 267.27999878, 239.42999268, 233.28999329,
       221.86000061, 272.20001221, 252.3999939 , 252.30999756,
       252.3500061 , 254.11000061, 241.55000305, 241.36999512,
       227.5       , 237.97000122, 250.74000549, 259.51000977,
       284.95001221, 285.88000488, 292.02999878, 282.16000366,
       280.51998901, 287.20999146, 280.26000977, 275.3500061 ,
       276.22000122, 284.82000732, 298.26000977, 318.38000488,
       334.07000732, 347.67999268, 342.82000732, 349.98001099,
       342.08999634, 343.82000732, 334.61999512, 341.04000854,
       339.33999634, 362.89001465, 356.8999939 , 358.42999268,
       346.45999146, 342.69000244, 344.26998901, 332.04998779,
       284.70001221, 295.14001465, 308.57998657, 326.08999634,
       326.42999268, 319.10998535, 325.30999756, 329.13000488,
       316.3500061 , 322.04998779, 322.16000366, 348.67999268,
       340.47000122, 327.54998779, 325.77999878, 323.63000488,
       317.66000366, 300.70999146, 315.6499939 , 315.3500061 ,
       293.94000244, 297.80999756, 295.88000488, 309.86999512,
       313.51000977, 316.8999939 , 310.77999878, 321.67001343,
       319.41000366, 329.6499939 , 328.48999023, 332.10998535,
       332.55999756, 305.29998779, 316.05999756, 325.58999634,
       321.20001221, 319.04000854, 308.26998901, 302.63000488,
       309.26000977, 308.72000122, 319.91000366, 322.26998901,
       329.6499939 , 339.02999878, 340.83999634, 339.38000488,
       335.57998657, 330.55999756, 335.16000366, 329.30999756,
       323.8999939 , 320.10998535, 340.01000977, 346.6000061 ,
       351.67001343, 349.6000061 , 345.98001099, 333.86999512,
       329.35998535, 334.08999634, 338.52999878, 350.83999634,
       346.3999939 , 346.97000122, 347.79000854, 368.80999756,
       395.94000244, 410.04000854, 421.61999512, 425.85998535,
       416.8500061 , 426.07000732, 434.20999146, 425.8500061 ,
       442.79000854, 423.39001465, 440.3999939 , 443.20999146,
       444.72000122, 459.45999146, 436.        , 429.82998657,
       453.25      , 433.08999634, 438.69000244, 435.54000854,
       413.48999023, 435.8999939 , 429.23999023, 435.1499939 ,
       428.75      , 439.30999756, 447.42999268, 442.6000061 ,
       438.97000122, 448.98001099, 433.72000122, 452.42001343,
       460.54998779, 461.51000977, 440.1000061 , 456.55999756,
       468.36999512, 444.26000977, 462.07000732, 445.91000366,
       429.51998901, 445.23001099, 439.61999512, 430.6000061 ,
       401.98999023, 404.3500061 , 408.92001343, 401.25      ,
       403.98999023, 395.23001099, 391.08999634, 417.77999878,
       419.3999939 , 426.57998657, 430.17001343, 430.14001465,
       429.23999023, 446.73999023, 454.52999878, 455.        ,
       439.57998657, 445.17001343, 451.45001221, 446.89001465,
       458.95999146, 475.30999756, 489.88000488, 467.26000977,
       483.36999512])

In [6]:
ind = df.index
ind

DatetimeIndex(['2022-08-19', '2022-08-22', '2022-08-23', '2022-08-24',
               '2022-08-25', '2022-08-26', '2022-08-29', '2022-08-30',
               '2022-08-31', '2022-09-01',
               ...
               '2025-12-05', '2025-12-08', '2025-12-09', '2025-12-10',
               '2025-12-11', '2025-12-12', '2025-12-15', '2025-12-16',
               '2025-12-17', '2025-12-18'],
              dtype='datetime64[ns]', name='Date', length=837, freq=None)

In [8]:
formats = [msft, google, meta, tesla]
formats

[array([286.1499939 , 277.75      , 276.44000244, 275.79000854,
        278.8500061 , 268.08999634, 265.23001099, 262.97000122,
        261.47000122, 260.3999939 , 256.05999756, 253.25      ,
        258.08999634, 258.51998901, 264.45999146, 266.6499939 ,
        251.99000549, 252.22000122, 245.38000488, 244.74000549,
        244.52000427, 242.44999695, 238.94999695, 240.97999573,
        237.91999817, 237.44999695, 236.41000366, 241.07000732,
        237.5       , 232.8999939 , 240.74000549, 248.88000488,
        249.19999695, 246.78999329, 234.24000549, 229.25      ,
        225.41000366, 225.75      , 234.24000549, 228.55999756,
        237.52999878, 238.5       , 236.47999573, 236.1499939 ,
        242.11999512, 247.25      , 250.66000366, 231.32000732,
        226.75      , 235.86999512, 232.13000488, 228.16999817,
        220.1000061 , 214.25      , 221.38999939, 227.86999512,
        228.86999512, 224.50999451, 242.97999573, 247.11000061,
        241.55000305, 241.97000122, 241.72999573, 241.67999268,
        241.22000122, 242.05000305, 245.02999878, 247.58000183,
        247.49000549, 241.75999451, 240.33000183, 255.13999939,
        254.69000244, 255.02000427, 250.19999695, 245.11999512,
        244.36999512, 247.3999939 , 245.41999817, 252.50999451,
        256.92001343, 257.22000122, 249.00999451, 244.69000244,
        240.44999695, 241.80000305, 244.42999268, 238.19000244,
        238.72999573, 236.96000671, 234.52999878, 241.00999451,
        239.82000732, 239.58000183, 229.1000061 , 222.30999756,
        224.92999268, 227.11999512, 228.8500061 , 235.77000427,
        238.50999451, 239.22999573, 240.3500061 , 235.80999756,
        231.92999268, 240.22000122, 242.58000183, 242.03999329,
        240.61000061, 248.        , 248.16000366, 242.71000671,
        247.80999756, 252.75      , 264.6000061 , 258.3500061 ,
        256.76998901, 267.55999756, 266.73001099, 263.61999512,
        263.1000061 , 271.32000732, 272.17001343, 269.32000732,
        262.1499939 , 258.05999756, 252.66999817, 251.50999451,
        254.77000427, 249.22000122, 250.16000366, 249.41999817,
        246.27000427, 251.11000061, 255.28999329, 256.86999512,
        254.1499939 , 253.69999695, 252.32000732, 248.58999634,
        253.91999817, 260.79000854, 265.44000244, 276.20001221,
        279.42999268, 272.23001099, 273.77999878, 272.29000854,
        277.66000366, 280.57000732, 276.38000488, 275.23001099,
        280.51000977, 284.04998779, 288.29998779, 287.23001099,
        287.17999268, 284.33999634, 291.6000061 , 289.39001465,
        282.82998657, 283.48999023, 289.83999634, 286.14001465,
        288.79998779, 288.36999512, 288.45001221, 286.10998535,
        285.76000977, 281.76998901, 275.42001343, 295.36999512,
        304.82998657, 307.26000977, 305.55999756, 305.41000366,
        304.3999939 , 305.41000366, 310.6499939 , 308.6499939 ,
        307.        , 312.30999756, 310.10998535, 308.97000122,
        309.45999146, 311.73999023, 314.        , 318.51998901,
        318.33999634, 321.17999268, 315.26000977, 313.8500061 ,
        325.92001343, 332.89001465, 331.20999146, 328.39001465,
        332.57998657, 335.3999939 , 335.94000244, 333.67999268,
        323.38000488, 325.26000977, 326.79000854, 331.8500061 ,
        334.29000854, 337.33999634, 348.1000061 , 342.32998657,
        338.04998779, 333.55999756, 339.70999146, 335.01998901,
        328.6000061 , 334.57000732, 335.8500061 , 335.04998779,
        340.54000854, 337.98999023, 338.1499939 , 341.26998901,
        337.22000122, 331.82998657, 332.47000122, 337.20001221,
        342.66000366, 345.23999023, 345.73001099, 359.48999023,
        355.07998657, 346.86999512, 343.76998901, 345.10998535,
        350.98001099, 337.76998901, 330.72000122, 338.36999512,
        335.92001343, 336.33999634, 327.5       , 326.66000366,
        327.77999878, 330.10998535, 326.04998779, 322.23001099,
        322.92999268, 321.01000977, 324.04000854, 321.85998535,
        320.3999939 , 316.88000488, 316.48001099, 321.88000488,
        322.45999146, 327.        , 319.97000122, 322.98001099,
        323.70001221, 328.41000366, 328.79000854, 327.76000977,
        328.66000366, 333.54998779, 332.88000488, 329.91000366,
        334.26998901, 337.94000244, 331.76998901, 336.05999756,
        338.70001221, 330.22000122, 329.05999756, 328.6499939 ,
        320.76998901, 319.52999878, 317.01000977, 317.54000854,
        312.14001465, 312.79000854, 313.64001465, 315.75      ,
        321.79998779, 313.39001465, 318.95999146, 319.35998535,
        327.26000977, 329.82000732, 328.39001465, 332.42001343,
        331.16000366, 327.73001099, 332.64001465, 332.05999756,
        330.10998535, 331.32000732, 326.67001343, 329.32000732,
        330.52999878, 340.67001343, 327.89001465, 329.80999756,
        337.30999756, 338.10998535, 346.07000732, 348.32000732,
        352.79998779, 356.52999878, 360.52999878, 363.20001221,
        360.69000244, 369.67001343, 366.67999268, 370.26998901,
        369.67001343, 376.17001343, 369.8500061 , 377.44000244,
        373.07000732, 377.8500061 , 377.42999268, 378.60998535,
        382.70001221, 378.8500061 , 378.91000366, 374.51000977,
        369.14001465, 372.51998901, 368.79998779, 370.95001221,
        374.23001099, 371.29998779, 374.38000488, 374.36999512,
        365.92999268, 370.73001099, 372.6499939 , 373.26000977,
        370.61999512, 373.54000854, 374.57998657, 374.66000366,
        374.07000732, 375.27999878, 376.04000854, 370.86999512,
        370.6000061 , 367.94000244, 367.75      , 374.69000244,
        375.79000854, 382.76998901, 384.63000488, 388.47000122,
        390.26998901, 389.47000122, 393.86999512, 398.67001343,
        396.51000977, 398.8999939 , 402.55999756, 404.86999512,
        403.92999268, 409.72000122, 408.58999634, 397.57998657,
        403.77999878, 411.22000122, 405.6499939 , 405.48999023,
        414.04998779, 414.10998535, 420.54998779, 415.26000977,
        406.32000732, 409.48999023, 406.55999756, 404.05999756,
        402.79000854, 402.17999268, 411.6499939 , 410.33999634,
        407.54000854, 407.48001099, 407.72000122, 413.64001465,
        415.5       , 414.92001343, 402.6499939 , 402.08999634,
        409.14001465, 406.22000122, 404.51998901, 415.27999878,
        415.1000061 , 425.22000122, 416.42001343, 417.32000732,
        421.41000366, 425.23001099, 429.36999512, 428.73999023,
        422.85998535, 421.6499939 , 421.42999268, 420.72000122,
        424.57000732, 421.44000244, 420.45001221, 417.88000488,
        425.51998901, 424.58999634, 426.27999878, 423.26000977,
        427.92999268, 421.8999939 , 413.64001465, 414.57998657,
        411.83999634, 404.26998901, 399.11999512, 400.95999146,
        407.57000732, 409.05999756, 399.04000854, 406.32000732,
        402.25      , 389.32998657, 394.94000244, 397.83999634,
        406.66000366, 413.54000854, 409.33999634, 410.54000854,
        412.32000732, 414.73999023, 413.72000122, 416.55999756,
        423.07998657, 420.98999023, 420.20999146, 425.33999634,
        429.04000854, 430.51998901, 427.        , 430.16000366,
        430.32000732, 429.17001343, 414.67001343, 415.13000488,
        413.51998901, 416.07000732, 424.01000977, 424.51998901,
        423.8500061 , 427.86999512, 432.67999268, 441.05999756,
        441.57998657, 442.57000732, 448.36999512, 446.33999634,
        445.70001221, 449.77999878, 447.67001343, 450.95001221,
        452.16000366, 452.8500061 , 446.95001221, 456.73001099,
        459.27999878, 460.76998901, 467.55999756, 466.23999023,
        459.54000854, 466.25      , 454.70001221, 453.54998779,
        453.95999146, 449.51998901, 443.51998901, 440.36999512,
        437.10998535, 442.94000244, 444.8500061 , 428.8999939 ,
        418.3999939 , 425.26998901, 426.73001099, 422.92001343,
        418.3500061 , 417.10998535, 408.48999023, 395.1499939 ,
        399.60998535, 398.42999268, 402.69000244, 406.01998901,
        406.80999756, 414.01000977, 416.85998535, 421.02999878,
        418.47000122, 421.52999878, 424.79998779, 424.14001465,
        415.54998779, 416.79000854, 413.48999023, 413.83999634,
        410.6000061 , 413.11999512, 417.14001465, 409.44000244,
        408.8999939 , 408.39001465, 401.70001221, 405.72000122,
        414.20001221, 423.04000854, 427.        , 430.58999634,
        431.33999634, 435.1499939 , 430.80999756, 438.69000244,
        435.26998901, 433.51000977, 429.17001343, 432.10998535,
        431.30999756, 428.01998901, 430.29998779, 420.69000244,
        417.13000488, 416.54000854, 416.05999756, 409.54000854,
        414.70999146, 417.45999146, 415.83999634, 416.32000732,
        419.14001465, 418.73999023, 416.11999512, 416.72000122,
        418.16000366, 418.77999878, 427.51000977, 424.6000061 ,
        424.73001099, 428.1499939 , 426.58999634, 431.95001221,
        432.52999878, 406.3500061 , 410.36999512, 408.45999146,
        411.45999146, 420.17999268, 425.42999268, 422.54000854,
        418.01000977, 423.02999878, 425.20001221, 426.89001465,
        415.        , 415.76000977, 417.79000854, 415.48999023,
        412.86999512, 417.        , 418.79000854, 427.98999023,
        422.98999023, 423.45999146, 430.98001099, 431.20001221,
        437.42001343, 442.61999512, 443.57000732, 446.01998901,
        443.32998657, 448.98999023, 449.55999756, 447.26998901,
        451.58999634, 454.45999146, 437.39001465, 437.02999878,
        436.6000061 , 435.25      , 439.32998657, 438.10998535,
        430.52999878, 424.82998657, 421.5       , 418.57998657,
        423.3500061 , 427.8500061 , 422.36999512, 424.55999756,
        418.95001221, 417.19000244, 415.67001343, 426.30999756,
        424.57998657, 429.02999878, 428.5       , 446.20001221,
        446.70999146, 444.05999756, 434.55999756, 447.20001221,
        442.32998657, 414.98999023, 415.05999756, 410.92001343,
        412.36999512, 413.29000854, 415.82000732, 409.75      ,
        412.22000122, 411.44000244, 409.04000854, 410.54000854,
        408.42999268, 409.64001465, 414.76998901, 416.13000488,
        408.20999146, 404.        , 397.8999939 , 399.73001099,
        392.52999878, 396.98999023, 388.48999023, 388.60998535,
        401.01998901, 396.89001465, 393.30999756, 380.16000366,
        380.45001221, 383.26998901, 378.76998901, 388.55999756,
        388.70001221, 383.51998901, 387.82000732, 386.83999634,
        391.26000977, 393.07998657, 395.16000366, 389.97000122,
        390.57998657, 378.79998779, 375.39001465, 382.19000244,
        382.14001465, 373.10998535, 359.83999634, 357.85998535,
        354.55999756, 390.48999023, 381.3500061 , 388.45001221,
        387.80999756, 385.73001099, 371.60998535, 367.77999878,
        359.11999512, 366.82000732, 374.39001465, 387.29998779,
        391.8500061 , 391.16000366, 394.04000854, 395.26000977,
        425.3999939 , 435.27999878, 436.17001343, 433.30999756,
        433.3500061 , 438.17001343, 438.73001099, 449.26000977,
        449.14001465, 452.94000244, 453.13000488, 454.26998901,
        458.86999512, 458.17001343, 452.57000732, 454.85998535,
        450.17999268, 460.69000244, 457.35998535, 458.67999268,
        460.35998535, 461.97000122, 462.97000122, 463.86999512,
        467.67999268, 470.38000488, 472.75      , 470.92001343,
        472.61999512, 478.86999512, 474.95999146, 479.14001465,
        478.04000854, 480.23999023, 477.3999939 , 486.        ,
        490.10998535, 492.26998901, 497.45001221, 495.94000244,
        497.41000366, 492.04998779, 491.08999634, 498.83999634,
        497.72000122, 496.61999512, 503.51000977, 501.48001099,
        503.32000732, 503.01998901, 505.82000732, 505.61999512,
        511.70001221, 510.04998779, 510.05999756, 505.26998901,
        505.86999512, 510.88000488, 513.71002197, 512.5       ,
        512.57000732, 513.23999023, 533.5       , 524.10998535,
        535.64001465, 527.75      , 524.94000244, 520.84002686,
        522.03997803, 521.77001953, 529.23999023, 520.58001709,
        522.47998047, 520.16998291, 517.09997559, 509.76998901,
        505.72000122, 504.23999023, 507.23001099, 504.26000977,
        502.04000854, 506.73999023, 509.64001465, 506.69000244,
        505.11999512, 505.3500061 , 507.97000122, 495.        ,
        498.20001221, 498.41000366, 500.36999512, 501.01000977,
        509.8999939 , 515.35998535, 509.04000854, 510.01998901,
        508.45001221, 517.92999268, 514.45001221, 509.23001099,
        510.1499939 , 507.02999878, 511.45999146, 514.59997559,
        517.95001221, 519.71002197, 515.73999023, 517.34997559,
        528.57000732, 523.97998047, 524.84997559, 522.40002441,
        510.95999146, 514.04998779, 513.57000732, 513.42999268,
        511.60998535, 513.58001709, 516.78997803, 517.65997314,
        520.53997803, 520.55999756, 523.60998535, 531.52001953,
        542.07000732, 541.54998779, 525.76000977, 517.80999756,
        517.0300293 , 514.33001709, 507.16000366, 497.1000061 ,
        496.82000732, 506.        , 508.67999268, 511.14001465,
        503.29000854, 510.17999268, 507.48999023, 493.79000854,
        487.11999512, 478.42999268, 472.11999512, 474.        ,
        476.98999023, 485.5       , 492.01000977, 486.73999023,
        490.        , 477.73001099, 480.83999634, 483.16000366,
        491.01998901, 492.01998901, 478.55999756, 483.47000122,
        478.52999878, 474.82000732, 476.39001465, 476.11999512,
        483.98001099]),
 array([118.12000275, 115.06999969, 114.76999664, 114.69999695,
        117.69999695, 111.30000305, 110.33999634, 109.91000366,
        109.15000153, 110.55000305, 108.68000031, 107.48000336,
        110.48000336, 109.41999817, 111.77999878, 111.87000275,
        105.30999756, 105.87000275, 103.90000153, 103.62999725,
        103.84999847, 101.83000183, 100.01000214, 100.56999969,
         99.16999817,  98.80999756,  98.08999634, 100.73999786,
         98.08999634,  96.15000153,  99.30000305, 102.41000366,
        102.22000122, 102.23999786,  99.56999969,  98.70999908,
         98.05000305,  98.30000305,  99.70999908,  97.18000031,
        100.77999878, 101.38999939, 100.29000092, 100.52999878,
        101.48000336, 102.97000122, 104.93000031,  94.81999969,
         92.59999847,  96.58000183,  94.66000366,  90.5       ,
         87.06999969,  83.48999786,  86.69999695,  88.65000153,
         88.91000366,  87.40000153,  94.16999817,  96.73000336,
         96.02999878,  98.72000122,  98.98999786,  98.5       ,
         97.80000305,  95.83000183,  97.33000183,  98.81999969,
         97.59999847,  96.25      ,  95.44000244, 101.44999695,
        101.27999878, 100.83000183,  99.87000275,  97.30999756,
         95.15000153,  93.94999695,  93.06999969,  93.55999756,
         95.84999847,  95.30999756,  91.19999695,  90.86000061,
         89.15000153,  89.62999725,  90.25      ,  88.26000214,
         89.80999756,  87.93000031,  86.45999908,  88.94999695,
         88.73000336,  89.69999695,  88.70999908,  86.76999664,
         88.16000366,  88.80000305,  89.23999786,  92.26000214,
         91.91000366,  92.80000305,  92.16000366,  91.77999878,
         93.91000366,  99.27999878, 101.20999908,  99.20999908,
         96.73000336,  99.16000366, 100.70999908,  97.94999695,
         99.87000275, 101.43000031, 108.80000305, 105.22000122,
        103.47000122, 108.04000092, 100.        ,  95.45999908,
         94.86000061,  95.        ,  94.94999695,  97.09999847,
         95.77999878,  94.58999634,  92.05000305,  91.80000305,
         91.06999969,  89.34999847,  90.09999847,  90.30000305,
         90.51000214,  92.30999756,  94.01999664,  95.58000183,
         94.16999817,  94.65000153,  92.66000366,  91.01000214,
         91.66000366,  94.25      ,  96.55000305, 101.06999969,
        102.45999908, 101.93000031, 105.83999634, 104.22000122,
        106.26000214, 106.05999756, 103.05999756, 101.36000061,
        101.90000153, 101.31999969, 104.        , 104.91000366,
        105.12000275, 104.94999695, 108.90000153, 106.94999695,
        106.12000275, 105.22000122, 108.19000244, 109.45999908,
        106.41999817, 105.12000275, 105.01999664, 105.90000153,
        105.91000366, 106.77999878, 104.61000061, 104.44999695,
        108.37000275, 108.22000122, 107.70999908, 105.98000336,
        106.12000275, 105.20999908, 106.21499634, 108.23999786,
        107.94000244, 112.27999878, 116.90000153, 117.91999817,
        116.95999908, 120.08999634, 121.48000336, 123.51999664,
        123.25      , 125.87000275, 123.29000092, 121.63999939,
        124.34999847, 125.43000031, 124.63999939, 123.37000275,
        124.37000275, 125.23000336, 126.62999725, 127.91000366,
        122.94000244, 122.66999817, 122.87000275, 124.34999847,
        124.43000031, 124.37999725, 125.79000092, 124.05999756,
        123.84999847, 121.26000214, 123.87000275, 123.01999664,
        119.08999634, 119.01000214, 121.08000183, 120.01000214,
        120.97000122, 120.55999756, 122.62999725, 120.93000031,
        120.13999939, 116.87000275, 117.70999908, 119.62000275,
        124.83000183, 125.69999695, 125.05999756, 124.08000183,
        122.77999878, 119.52999878, 120.30999756, 121.87999725,
        122.79000092, 129.66000366, 129.86999512, 133.00999451,
        133.11000061, 131.88999939, 128.63999939, 128.77000427,
        128.53999329, 131.94000244, 131.83999634, 130.1499939 ,
        130.21000671, 130.16999817, 131.83000183, 130.27000427,
        129.11000061, 130.46000671, 128.11000061, 128.92999268,
        129.69000244, 133.21000671, 130.41999817, 130.69000244,
        131.78999329, 135.49000549, 136.92999268, 137.3500061 ,
        136.80000305, 136.71000671, 135.36999512, 136.19999695,
        137.19999695, 137.74000549, 136.07000732, 137.5       ,
        138.99000549, 138.30000305, 138.96000671, 138.83000183,
        134.58999634, 131.36000061, 131.25      , 132.16999817,
        129.44999695, 131.46000671, 133.13000488, 131.8500061 ,
        135.16999817, 133.30000305, 136.27000427, 135.99000549,
        138.72999573, 139.5       , 139.19999695, 141.69999695,
        140.28999329, 138.58000183, 140.49000549, 140.99000549,
        139.27999878, 138.97999573, 136.74000549, 137.8999939 ,
        140.11999512, 126.66999817, 123.44000244, 123.40000153,
        125.75      , 125.30000305, 127.56999969, 128.58000183,
        130.36999512, 131.44999695, 132.3999939 , 133.25999451,
        131.69000244, 134.05999756, 133.63999939, 135.42999268,
        136.38000488, 138.69999695, 136.94000244, 137.91999817,
        138.61999512, 140.02000427, 138.22000122, 138.05000305,
        138.61999512, 136.3999939 , 133.91999817, 133.32000732,
        130.63000488, 132.38999939, 131.42999268, 138.44999695,
        136.63999939, 134.69999695, 133.63999939, 133.97000122,
        133.19999695, 133.83999634, 137.19000244, 138.1000061 ,
        139.66000366, 141.80000305, 142.72000122, 142.82000732,
        141.44000244, 141.27999878, 140.92999268, 139.55999756,
        140.36000061, 138.03999329, 137.38999939, 140.52999878,
        142.55999756, 143.80000305, 143.66999817, 144.24000549,
        144.08000183, 142.88999939, 144.99000549, 147.97000122,
        147.71000671, 148.67999268, 150.3500061 , 153.63999939,
        153.78999329, 154.83999634, 153.05000305, 141.80000305,
        142.71000671, 143.53999329, 144.92999268, 145.41000366,
        146.67999268, 147.22000122, 150.22000122, 148.72999573,
        146.36999512, 147.13999939, 143.94000244, 141.75999451,
        142.19999695, 143.83999634, 145.32000732, 145.28999329,
        138.75      , 140.1000061 , 137.42999268, 139.77999878,
        138.08000183, 134.19999695, 133.77999878, 132.55999756,
        135.24000549, 136.28999329, 138.94000244, 139.61999512,
        140.77000427, 144.33999634, 142.16999817, 148.47999573,
        147.91999817, 149.67999268, 148.74000549, 151.77000427,
        151.1499939 , 151.69999695, 151.94000244, 152.25999451,
        156.5       , 155.86999512, 156.36999512, 151.94000244,
        153.94000244, 156.13999939, 158.13999939, 157.66000366,

In [21]:
data = pd.DataFrame(formats)
data = data.transpose()
data.columns = ['msft', 'google', 'meta', 'tesla']
data

           msft      google        meta       tesla
0    286.149994  118.120003  167.960007  296.666656
1    277.750000  115.070000  163.050003  289.913330
2    276.440002  114.769997  161.110001  296.453339
3    275.790009  114.699997  163.259995  297.096680
4    278.850006  117.699997  168.779999  296.070007
..          ...         ...         ...         ...
832  478.529999  310.519989  644.229980  458.959991
833  474.820007  309.320007  647.510010  475.309998
834  476.390015  307.730011  657.150024  489.880005
835  476.119995  298.059998  649.500000  467.260010
836  483.980011  303.750000  664.450012  483.369995

[837 rows x 4 columns]

In [22]:
data = data.set_index(ind)
data

                  msft      google        meta       tesla
Date
2022-08-19  286.149994  118.120003  167.960007  296.666656
2022-08-22  277.750000  115.070000  163.050003  289.913330
2022-08-23  276.440002  114.769997  161.110001  296.453339
2022-08-24  275.790009  114.699997  163.259995  297.096680
2022-08-25  278.850006  117.699997  168.779999  296.070007
...                ...         ...         ...         ...
2025-12-12  478.529999  310.519989  644.229980  458.959991
2025-12-15  474.820007  309.320007  647.510010  475.309998
2025-12-16  476.390015  307.730011  657.150024  489.880005
2025-12-17  476.119995  298.059998  649.500000  467.260010
2025-12-18  483.980011  303.750000  664.450012  483.369995

[837 rows x 4 columns]

In [23]:
data.to_csv("stock_data.csv")